import { createPhysicalChemicalKernel } from './core/physical-chemical-kernel.js';

const C=48,R=24,N=C*R,$=id=>document.getElementById(id),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const canvas=$('chemMap'),ctx=canvas.getContext('2d'),hcan=$('history'),hctx=hcan.getContext('2d');
let seed=Number(new URLSearchParams(location.search).get('seed'))||4400777,paused=false,field='organics',selected=Math.floor(N/2),frame=0,history=[];
const meta={
 organics:['ORGANIC CHEMISTRY','field','organics'],amphiphiles:['AMPHIPHILES','field','amphiphiles'],precursors:['REACTIVE PRECURSORS','field','precursors'],complexity:['CHEMICAL DIVERSITY','field','complexity'],energyFlux:['FREE-ENERGY FLUX','field','energyFlux'],
 water:['SURFACE WATER','env','water'],hydrothermal:['HYDROTHERMAL ACTIVITY','env','hydrothermal'],wetDry:['WET–DRY CYCLING','env','wetDry'],ultraviolet:['ULTRAVIOLET','env','ultraviolet'],
 hydrogen:['H₂','species','hydrogen'],carbonDioxide:['CO₂','species','carbonDioxide'],ammonia:['NH₃','species','ammonia'],methane:['CH₄','species','methane'],reducedCarbon:['REDUCED CARBON','species','reducedCarbon'],formamide:['FORMAMIDE-LIKE','species','formamide'],phosphate:['PHOSPHATE','species','phosphate']};
const order=Object.keys(meta),speciesNames=['hydrogen','carbonDioxide','carbonMonoxide','nitrogen','ammonia','hydrogenSulfide','phosphate','methane','reducedCarbon','formamide','amphiphile','condensate'];
const label={water:'H₂O',hydrogen:'H₂',carbonDioxide:'CO₂',carbonMonoxide:'CO',nitrogen:'N₂',ammonia:'NH₃',hydrogenSulfide:'H₂S',ferrousOxide:'FeO',magnetite:'Fe₃O₄',phosphate:'phosphate',methane:'CH₄',reducedCarbon:'reduced C',formamide:'CH₃NO',amphiphile:'amphiphile',condensate:'N-condensate'};
let env,kernel;

function noise(x,y,s){let h=(Math.imul(x,374761393)+Math.imul(y,668265263)+Math.imul(s|0,1442695041))|0;h=Math.imul(h^(h>>>13),1274126177);return((h^(h>>>16))>>>0)/4294967295}
function smoothNoise(x,y,s){const x0=Math.floor(x),y0=Math.floor(y),tx=x-x0,ty=y-y0,a=noise(x0,y0,s),b=noise(x0+1,y0,s),c=noise(x0,y0+1,s),d=noise(x0+1,y0+1,s),sx=tx*tx*(3-2*tx),sy=ty*ty*(3-2*ty);return(a*(1-sx)+b*sx)*(1-sy)+(c*(1-sx)+d*sx)*sy}
function fractal(x,y,s){return smoothNoise(x,y,s)*.62+smoothNoise(x*2.1,y*2.1,s^991)*.27+smoothNoise(x*4.2,y*4.2,s^1777)*.11}
function build(){env={water:new Float32Array(N),minerals:new Float32Array(N),hydrothermal:new Float32Array(N),wetDry:new Float32Array(N),ultraviolet:new Float32Array(N),temperature:new Float32Array(N)};for(let r=0;r<R;r++)for(let c=0;c<C;c++){const i=r*C+c,u=(c+.5)/C,v=(r+.5)/R,lat=(.5-v)*Math.PI,cont=fractal(u*4.2,v*3.1,seed)+Math.sin(u*19+v*4)*.11,land=cont>.5,coast=clamp(1-Math.abs(cont-.5)*12),plate=clamp((fractal(u*10,v*7,seed^83)-.45)*1.9),vent=clamp(plate*.8+fractal(u*17,v*12,seed^31)*.22-.05),rain=clamp(.48+Math.cos(lat)*.3+fractal(u*7,v*5,seed^7)*.2);env.water[i]=land?clamp(coast*.35+rain*.14,.02,.58):1;env.wetDry[i]=clamp(coast*.82+(land?rain*.22:.03));env.hydrothermal[i]=vent;env.minerals[i]=clamp(.18+plate*.67+cont*.18);env.temperature[i]=clamp(.3+Math.cos(lat)*.4+vent*.12);env.ultraviolet[i]=clamp(.25+Math.cos(lat)*.68,.04,1.2)}kernel=createPhysicalChemicalKernel({columns:C,rows:R,seed:seed^0x51F15EED,star:{metallicity:-.03},disk:{carbonToOxygen:.54},planet:{composition:'silicate-rocky',atmosphereRetention:.63,waterFraction:.34,equilibriumTemperature:286,massEarth:.96},environment:env});for(let i=0;i<12;i++)kernel.step(.45);history=[];capture();render()}
function data(name){const[,g,k]=meta[name];return g==='field'?kernel.getFields()[k]:g==='env'?env[k]:kernel.getSpecies()[k]}
function palette(t){const s=[[5,8,20],[21,51,79],[14,124,121],[124,207,123],[240,213,96],[255,123,79],[247,244,232]],x=clamp(t)*(s.length-1),i=Math.min(s.length-2,Math.floor(x)),f=x-i,a=s[i],b=s[i+1];return`rgb(${Math.round(a[0]+(b[0]-a[0])*f)},${Math.round(a[1]+(b[1]-a[1])*f)},${Math.round(a[2]+(b[2]-a[2])*f)})`}
function drawMap(){const a=data(field),w=canvas.width/C,h=canvas.height/R;let max=1;if(meta[field][1]==='species'){max=0;for(const v of a)max=Math.max(max,v);max=Math.max(max,1e-8)}for(let r=0;r<R;r++)for(let c=0;c<C;c++){const i=r*C+c;let t=a[i]/max;if(meta[field][1]==='species')t=Math.log10(1+99*clamp(t))/2;ctx.fillStyle=palette(t);ctx.fillRect(c*w,r*h,w+1,h+1)}const r=Math.floor(selected/C),c=selected%C;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.strokeRect(c*w+1,r*h+1,w-2,h-2);$('mapTitle').textContent=meta[field][0]}
function pct(v){return`${(clamp(v)*100).toFixed(v<.01?2:1)}%`}function num(v){return v&&Math.abs(v)<1e-4?v.toExponential(2):(v||0).toFixed(5)}
function inspector(){const f=kernel.getFields(),s=kernel.getSpecies(),r=Math.floor(selected/C),c=selected%C;$('cellCoord').textContent=`${(90-(r+.5)/R*180).toFixed(1)}°, ${((c+.5)/C*360-180).toFixed(1)}°`;$('cellEnv').innerHTML=[['Temperature',`${f.temperatureK[selected].toFixed(1)} K`],['Pressure',`${f.pressureBar[selected].toFixed(2)} bar`],['Free energy',num(f.energyFlux[selected])],['Water',pct(env.water[selected])],['Minerals',pct(env.minerals[selected])],['Hydrothermal',pct(env.hydrothermal[selected])],['Wet–dry',pct(env.wetDry[selected])]].map(x=>`<span>${x[0]}</span><b>${x[1]}</b>`).join('');$('speciesGrid').innerHTML=speciesNames.map(n=>`<div class="sp"><small>${label[n]||n}</small><b>${num(s[n][selected])}</b></div>`).join('');const rx=kernel.getReactionDefinitions().map(q=>{let a=1;for(const[n,k]of Object.entries(q.reactants))a*=Math.pow(s[n][selected]/(s[n][selected]+.02),1/Math.max(1,k));return[q,clamp(a*(.35+f.energyFlux[selected]*.85))]}).sort((a,b)=>b[1]-a[1]);$('reactionList').innerHTML=rx.map(([q,a])=>`<div class="reaction"><div class="name">${q.id.replaceAll('-',' ')}</div><div class="eq">${side(q.reactants)} → ${side(q.products)}</div><div class="bar"><i style="width:${a*100}%"></i></div></div>`).join('')}
function side(x){return Object.entries(x).map(([n,k])=>`${k===1?'':k+' '}${label[n]||n}`).join(' + ')}
function metrics(){const m=kernel.getMetrics(),led=kernel.getExportedElementLedger();$('mOrganics').textContent=pct(m.organics);$('mAmphiphiles').textContent=pct(m.amphiphiles);$('mPrecursors').textContent=pct(m.precursors);$('mComplexity').textContent=pct(m.complexity);$('mDrift').textContent=m.maxElementDrift.toExponential(1);$('mDrift').className=m.maxElementDrift<1e-8?'good':'warn';$('clockLabel').textContent=`chemistry time ${m.clock.toFixed(1)} · seed ${seed}`;$('ledger').innerHTML=[['Element conservation',m.maxElementDrift<1e-8?'stable':'check'],['Active chemistry',pct(m.activeChemistryCoverage)],['Energy consumed',num(m.reactionEnergyUse)],['Reaction heat',num(m.reactionHeat)],['C → biology',num(led.C)],['N → biology',num(led.N)],['P → biology',num(led.P)]].map(x=>`<span>${x[0]}</span><b>${x[1]}</b>`).join('')}
function capture(){const m=kernel.getMetrics();history.push([m.organics,m.amphiphiles,m.precursors]);if(history.length>180)history.shift()}
function chart(){const w=hcan.width,h=hcan.height;hctx.clearRect(0,0,w,h);const colors=['#88d8bd','#f2cf6f','#e58bc9'];for(let k=0;k<3;k++){let max=.02;for(const p of history)max=Math.max(max,p[k]);hctx.beginPath();history.forEach((p,i)=>{const x=i/Math.max(1,history.length-1)*w,y=h-6-clamp(p[k]/max)*(h-12);i?hctx.lineTo(x,y):hctx.moveTo(x,y)});hctx.strokeStyle=colors[k];hctx.lineWidth=2.4;hctx.stroke()}}
function render(){drawMap();inspector();metrics();chart()}
$('fieldButtons').innerHTML=order.map(n=>`<button data-f="${n}" class="${n===field?'active':''}">${meta[n][0]}</button>`).join('');$('fieldButtons').onclick=e=>{const b=e.target.closest('[data-f]');if(!b)return;field=b.dataset.f;[...$('fieldButtons').children].forEach(x=>x.classList.toggle('active',x===b));drawMap()};canvas.onpointerdown=e=>{const b=canvas.getBoundingClientRect(),c=clamp(Math.floor((e.clientX-b.left)/b.width*C),0,C-1),r=clamp(Math.floor((e.clientY-b.top)/b.height*R),0,R-1);selected=r*C+c;render()};$('pauseBtn').onclick=e=>{paused=!paused;e.currentTarget.textContent=paused?'Resume':'Pause'};$('stepBtn').onclick=()=>{kernel.step(.35);capture();render()};$('resetBtn').onclick=()=>{seed=(seed+777)>>>0;build()};
function loop(){if(!paused){const speed=+$('speed').value||1,n=Math.min(12,Math.ceil(speed/2)),dt=clamp(speed/n*.08,.04,.6);for(let i=0;i<n;i++)kernel.step(dt);if(frame++%5===0)capture()}render();requestAnimationFrame(loop)}
build();window.realitySandboxChemistryLab={get kernel(){return kernel},get environment(){return env},snapshot:()=>({seed,selected,field,metrics:kernel.getMetrics()})};requestAnimationFrame(loop);
