import { createExperimentRun } from '../experiment/run-single.js';

const $ = id => document.getElementById(id), clamp = (v, a = 0, b = 1) => Math.max(a, Math.min(b, v));
const map = $('map'), ctx = map.getContext('2d'), hist = $('history'), hctx = hist.getContext('2d');
const fieldMeta = {
  organics:['Organics','field'],amphiphiles:['Amphiphiles','field'],precursors:['Precursors','field'],complexity:['Chemical diversity','field'],energyFlux:['Free-energy flux','field'],compartmentPotential:['Compartment potential','field'],selfMaintenance:['Self-maintenance','field'],
  polymers:['All polymers','evolution'],freePolymers:['Free polymers','evolution'],variants:['Sequence variants','evolution'],heredity:['Heredity','evolution'],replication:['Replication','evolution'],selection:['Selection','evolution'],
  water:['Water','env'],hydrothermal:['Hydrothermal','env'],wetDry:['Wet/dry','env'],ultraviolet:['UV','env'],
  hydrogen:['H₂','species'],carbonDioxide:['CO₂','species'],ammonia:['NH₃','species'],methane:['CH₄','species'],reducedCarbon:['Reduced carbon','species'],formamide:['Formamide-like','species'],phosphate:['Phosphate','species']
};
const speciesNames=['hydrogen','carbonDioxide','carbonMonoxide','nitrogen','ammonia','hydrogenSulfide','phosphate','methane','reducedCarbon','formamide','amphiphile','condensate'];
const labels={hydrogen:'H₂',carbonDioxide:'CO₂',carbonMonoxide:'CO',nitrogen:'N₂',ammonia:'NH₃',hydrogenSulfide:'H₂S',phosphate:'PO₄ pool',methane:'CH₄',reducedCarbon:'reduced C',formamide:'CH₃NO',amphiphile:'amphiphile',condensate:'N-condensate'};
let seed=4400777, run, paused=false, auto=false, field='organics', selected=0, archived=[], chartHistory=[];

function start(newSeed=seed){seed=newSeed;run=createExperimentRun({seed,cutoff:+$('cutoff').value||500,dt:.25,columns:48,rows:24,captureEvery:4});selected=Math.floor(run.getKernel().getGrid().size/2);chartHistory=[];render()}
function dataset(){const k=run.getKernel(),group=fieldMeta[field][1];return group==='field'?k.getFields()[field]:group==='env'?run.getEnvironment()[field]:group==='evolution'?run.getEvolution().getFields()[field]:k.getSpecies()[field]}
function palette(t){const stops=[[3,7,14],[14,52,76],[10,113,108],[83,178,113],[224,205,91],[244,117,72],[246,240,218]],x=clamp(t)*(stops.length-1),i=Math.min(stops.length-2,Math.floor(x)),f=x-i,a=stops[i],b=stops[i+1];return`rgb(${Math.round(a[0]+(b[0]-a[0])*f)},${Math.round(a[1]+(b[1]-a[1])*f)},${Math.round(a[2]+(b[2]-a[2])*f)})`}
function drawMap(){const k=run.getKernel(),{columns:C,rows:R}=k.getGrid(),data=dataset();let max=1;if(fieldMeta[field][1]==='species'||(fieldMeta[field][1]==='evolution'&&['polymers','freePolymers','variants'].includes(field))){max=1e-9;for(const v of data)max=Math.max(max,v)}const w=map.width/C,h=map.height/R;for(let r=0;r<R;r++)for(let c=0;c<C;c++){const i=r*C+c;let t=data[i]/max;if(fieldMeta[field][1]==='species'||(fieldMeta[field][1]==='evolution'&&['polymers','freePolymers','variants'].includes(field)))t=Math.log10(1+99*clamp(t))/2;ctx.fillStyle=palette(t);ctx.fillRect(c*w,r*h,w+1,h+1)}const r=Math.floor(selected/C),c=selected%C;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.strokeRect(c*w+1,r*h+1,w-2,h-2)}
const pct=v=>`${(clamp(v)*100).toFixed(v<.01?2:1)}%`,num=v=>(v&&Math.abs(v)<1e-4?v.toExponential(2):(v||0).toFixed(5));
function inspect(){const k=run.getKernel(),f=k.getFields(),s=k.getSpecies(),e=run.getEnvironment(),ev=run.getEvolution(),ef=ev.getFields();$('env').innerHTML=[['T',`${f.temperatureK[selected].toFixed(1)} K`],['P',`${f.pressureBar[selected].toFixed(2)} bar`],['Energy',num(f.energyFlux[selected])],['Water',pct(e.water[selected])],['Minerals',pct(e.minerals[selected])],['Hydrothermal',pct(e.hydrothermal[selected])],['Wet/dry',pct(e.wetDry[selected])],['UV',pct(e.ultraviolet[selected])]].map(([a,b])=>`<span>${a}</span><b>${b}</b>`).join('');$('species').innerHTML=speciesNames.map(n=>`<div class="sp"><small>${labels[n]}</small><b>${num(s[n][selected])}</b></div>`).join('');const comps=ev.getCompartments().filter(c=>c.cell===selected),free=ev.getFreePolymers(selected);$('polymerState').innerHTML=[['free polymers',String(Math.round(ef.freePolymers[selected]))],['all polymers',String(Math.round(ef.polymers[selected]))],['variants',String(Math.round(ef.variants[selected]))],['compartments',String(comps.length)],['heredity',pct(ef.heredity[selected])],['replication',pct(ef.replication[selected])],['selection',pct(ef.selection[selected])]].map(([a,b])=>`<span>${a}</span><b>${b}</b>`).join('');const seq=[...free.map(x=>({...x,where:'surface'})),...comps.flatMap(c=>c.variants.map(x=>({...x,where:`vesicle ${c.id}`})))].sort((a,b)=>b.count-a.count).slice(0,14);$('polymerSeq').textContent=seq.length?seq.map(x=>`${x.where}  ${x.sequence}  ×${x.count}  gen ${x.generation}`).join('\n'):'No polymers in this cell.';const rx=k.getReactionDefinitions().map(q=>{let a=1;for(const[n,c]of Object.entries(q.reactants))a*=Math.pow(s[n][selected]/(s[n][selected]+.02),1/Math.max(1,c));return[q,clamp(a*(.3+f.energyFlux[selected]))]}).sort((a,b)=>b[1]-a[1]);$('reactions').innerHTML=rx.slice(0,7).map(([q,a])=>`<div class="reaction"><div>${q.id.replaceAll('-',' ')}</div><div class="bar"><i style="width:${a*100}%"></i></div></div>`).join('')}
function chart(){const w=hist.width,h=hist.height;hctx.clearRect(0,0,w,h);const keys=['organics','amphiphiles','candidate'],colors=['#7dd6b0','#e6cb71','#e78ad0'];keys.forEach((key,k)=>{let max=.02;for(const p of chartHistory)max=Math.max(max,p[key]);hctx.beginPath();chartHistory.forEach((p,i)=>{const x=i/Math.max(1,chartHistory.length-1)*w,y=h-5-clamp(p[key]/max)*(h-10);i?hctx.lineTo(x,y):hctx.moveTo(x,y)});hctx.strokeStyle=colors[k];hctx.lineWidth=2;hctx.stroke()})}
function render(){const snap=run.snapshot(),m=snap.metrics,d=snap.detection,b=snap.bestDetection,ev=snap.evolution;$('mOrg').textContent=pct(m.organics);$('mAmp').textContent=pct(m.amphiphiles);$('mCx').textContent=pct(m.complexity);$('mCandidate').textContent=pct(d.candidateScore);$('mDrift').textContent=m.maxElementDrift.toExponential(1);$('mPoly').textContent=String(Math.round(ev.polymerPopulation||0));$('mVar').textContent=String(Math.round(ev.sequenceVariants||0));$('mHer').textContent=pct(ev.heredity||0);$('mRep').textContent=pct(ev.replication||0);$('mSel').textContent=pct(ev.selection||0);$('runStatus').textContent=`best ${b.classification} · current ${d.classification} · t=${m.clock.toFixed(1)} · seed ${seed}`;$('runStatus').className='status '+(b.lifeDetected?'good':b.classification==='transient-replicator'||b.candidateDetected?'warn':'');$('experiment').innerHTML=[['best classification',b.classification],['current',d.classification],['life detected',String(b.lifeDetected)],['polymer peak',String(ev.peakPolymerPopulation||0)],['templated copies',String(ev.totalTemplatedBirths||0)],['mutations',String(ev.totalMutations||0)],['max polymer gen',String(ev.peakGenerations||0)],['cutoff',String(snap.cutoff)],['completed runs',String(archived.length)],['auto rerun',auto?'ON':'OFF']].map(([a,b])=>`<span>${a}</span><b>${b}</b>`).join('');$('archive').textContent=archived.slice(-12).reverse().map(x=>`${x.seed}: ${x.classification} @ ${x.clock.toFixed(1)} · peak polymers ${x.evolution?.peakPolymerPopulation||0} · copies ${x.evolution?.totalTemplatedBirths||0}`).join('\n')||'No archived runs yet.';drawMap();inspect();chart()}
function archiveAndMaybeRestart(){const final=run.getFinal();if(final&&!archived.some(x=>x.seed===final.seed))archived.push(final);if(auto&&final){start((Number(seed)+777)>>>0);return true}return false}
function loop(){if(!paused){const speed=+$('speed').value||1;const n=Math.min(30,Math.max(1,Math.ceil(speed/2)));for(let i=0;i<n&&!run.snapshot().finished;i++)run.step(Math.max(1,Math.round(speed/n)));const s=run.snapshot();chartHistory.push({organics:s.metrics.organics,amphiphiles:s.metrics.amphiphiles,candidate:s.detection.candidateScore});if(chartHistory.length>180)chartHistory.shift();if(s.finished&&archiveAndMaybeRestart()){} }render();requestAnimationFrame(loop)}
$('fields').innerHTML=Object.entries(fieldMeta).map(([key,[label]])=>`<button data-field="${key}" class="${key===field?'active':''}">${label}</button>`).join('');$('fields').onclick=e=>{const b=e.target.closest('[data-field]');if(!b)return;field=b.dataset.field;[...$('fields').children].forEach(x=>x.classList.toggle('active',x===b));render()};map.onpointerdown=e=>{const b=map.getBoundingClientRect(),g=run.getKernel().getGrid(),c=clamp(Math.floor((e.clientX-b.left)/b.width*g.columns),0,g.columns-1),r=clamp(Math.floor((e.clientY-b.top)/b.height*g.rows),0,g.rows-1);selected=r*g.columns+c;render()};$('pause').onclick=e=>{paused=!paused;e.currentTarget.textContent=paused?'Resume':'Pause'};$('step').onclick=()=>{run.step(1);render()};$('newSeed').onclick=()=>start((Number(seed)+777)>>>0);$('auto').onclick=e=>{auto=!auto;e.currentTarget.textContent=`Auto-rerun: ${auto?'ON':'OFF'}`};$('cutoff').onchange=()=>start(seed);
start();requestAnimationFrame(loop);window.abiogenesisLab={get run(){return run},get archive(){return archived},start};
